% This file is originally Yuksel Yabansu's.
% It has been edited by Noah Paulson for learning purposes

function inpgenerator()

el=21;
na=1;
set_id = 'trial1';

nodesets(el);
fprintf('Data set loaded\n')

% creating microstructures
M=zeros(el^3,na);

% % assign volume fractions from (min,max,...)
% vf=linspace(0.01,0.99,na-2);
vf = 0.5;

% generate two different sets of elements

for ii=1:na
    % randperm scrambles a vector of numbers
    Mp=randperm(el^3).';
    Mr=zeros(el^3,1);
    % assign 1s to indices with value greater than vf
    Mr(Mp<vf*el^3)=1;
    M(:,ii)=Mr;
end

save M_Ti-alpha-beta.mat M

orientationgenerator(na, set_id, M)


first50=fopen('50top.inp','r');
bottom50=fopen('50bottom.inp','r');
periodic=fopen('periodicCE.inp','r');

A=fread(first50,inf);
B=fread(bottom50,inf);
P=fread(periodic,inf);

fclose(first50);
fclose(bottom50);
fclose(periodic);

nodesetspbc=fopen('nodesets.inp','r');
nodesetspbcx=fread(nodesetspbc,inf);
fclose(nodesetspbc);
fclose('all');

for ii=1:na
    twopstatset(ii,M); %generate inp files for elset designation
    matsets=fopen(['matset' int2str(ii) '.inp'],'r'); %open .inp file
    % generated by twopstatset
    materset=fread(matsets,inf);
    combined=fopen(['hcp_200s_' int2str(ii) 'val.inp'],'w+');
    fwrite(combined,A); %write first50.inp to combined
    fprintf(combined,'\n');
    fwrite(combined,nodesetspbcx); %write the nodeset info to combined
    fprintf(combined,'\n');
    fwrite(combined,materset); %write the elset designation .inp info to
    %combined
    fprintf(combined,'\n');
    fwrite(combined,P); %write the periodic boundary condition .inp info to
    %combined
    fprintf(combined,'\n');
    includeorientationline(ii); %write info for where to get orientations
    % for .inp file
    include=['orienta' int2str(ii) '.inp'];
    incl=fopen(include,'r');
    D=fread(incl,inf);
    fwrite(combined,D);
    fprintf(combined,'\n');
    fwrite(combined,B); %write bottom50.inp to combined
    % close out of the .inp text files
    fclose(matsets);
    fclose(combined);
    fclose(incl);
    % delete temporary files generated by the includeorientationline()
    % and twopstatset() functions
    delete(include);
    materialsets=['matset' int2str(ii) '.inp'];
    delete(materialsets);
    fprintf('Done inp %i\n',ii)
end

fclose('all');